### ISSUE TITLE
Bluetooth permission check in Android <= 30

### ISSUE THREAD

**Issue by robbeman** [orbital-systems/react-native-esp-idf-provisioning#18]
The `BLUETOOTH_CONNECT` permission does not exist on Android <= 30, so this will always fail.

https://github.com/orbital-systems/react-native-esp-idf-provisioning/blob/b0e240de206abb27a1b7ce46a656d12540c2d89c/android/src/main/java/com/espidfprovisioning/EspIdfProvisioningModule.kt#L161

In fact permission checks seem a bit inconsistent in general. 🤔

---

Sidenote: It seems you do not need to grant permissions on lower android version, but maybe the permission checks are usefull to ensure bluetooth is enabled in general?

cfr. https://github.com/zoontek/react-native-permissions/issues/468

**Comment by mateogianolio** [comment]
Thanks for clearing this up! I can currently only test for Android >30 at work so I naively assumed it would return PERMISSION_GRANTED for <= 30.

As for the sidenote; yeah I think it could be useful for developers to know if their users have accidentally disabled bluetooth permissions in system/app settings. But as I can't test lower android versions right now, it's hard to know if the current check is sufficient.

**Comment by mateogianolio** [comment]
Released in version 0.2.9, feel free to open again.
