### ISSUE TITLE
Difference between this and similar libraries

### ISSUE THREAD

**Issue by grasmash** [orbital-systems/react-native-esp-idf-provisioning#29]
Thank you for creating this library. It maybe helpful for adoption to explain why one should choose this library compared to similar ones. Some examples:

* https://github.com/manbomb/esp-idf-ble-provisioning-rn
* https://github.com/amoghpalnitkar/react-native-esp-idf-provisioning
* https://github.com/kafudev/react-native-esp-idf
* https://github.com/futuristiclabs/react-native-esp32-idf

**Comment by mateogianolio** [comment]
Hey! Great idea.

**Comment by mateogianolio** [comment]
Added an explanation for why we created our own library here: #41. What do you think? :)
