### ISSUE TITLE
Unable to scan for wifi list on iOS

### ISSUE THREAD

**Issue by grasmash** [orbital-systems/react-native-esp-idf-provisioning#33]
Hello,

I've successfully used this library to find and connect to an ESP32 device. However, I'm not able to scan for a wifi list using the device connection. It returns the error:
```
[Error: Request for returning Wi-Fi network list failed with error: The operation couldn’t be completed. (SwiftProtobuf.BinaryDecodingError error 3.)]
```

Very simple implemenation:
```
#  This line works. Confirmed connection by monitoring ESP32 output.
await device.connect(proofOfPosession, null, username);
# This line produces an error.
const espWifiList = await device.scanWifiList();
```

**Comment by mateogianolio** [comment]
Hey there, I think this is related to #22 reported by @robbeman and his issue here: https://github.com/espressif/esp-idf-provisioning-ios/issues/74
