### ISSUE TITLE
scanWifiList never succeed if proofOfPossession is used 

### ISSUE THREAD

**Issue by tri-bao** [orbital-systems/react-native-esp-idf-provisioning#35]
Our app follows the example app. searchESPDevices works, we can see list of devices.

On a found device, we call `await espDevice.connect(proofOfPossession);`

Then call `await device.scanWifiList();` This always fails with message `Failed to create session`.

Logcat show `onCharacteristicWrite, status : 4`
And stack trace
```
java.lang.Exception: Write to BLE failed
at com.espressif.provisioning.transport.BLETransport$1.onCharacteristicWrite(BLETransport.java:377)
at android.bluetooth.BluetoothGatt$1$7.run(BluetoothGatt.java:562)
at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:959)
at android.bluetooth.BluetoothGatt.-$$Nest$mrunOrQueueCallback(Unknown Source:0)
at android.bluetooth.BluetoothGatt$1.onCharacteristicWrite(BluetoothGatt.java:557)
at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:279)
at android.os.Binder.execTransactInternal(Binder.java:1351)
at android.os.Binder.execTransact(Binder.java:1310)
```

I found that the android native property `ESPDevice.proofOfPossession` is always an empty string which make it unable to create BLE session with the device, hence the error above.

The reason is:
* in method `onPeripheralFound`, whenever a device is found (via `searchESPDevices`), it is added to the `espDevices` cache. But it that time, there is no PoP, thus no thing is set. Here is [the line](https://github.com/orbital-systems/react-native-esp-idf-provisioning/blob/7a08cc20b0dc1e2c6a55ae240fd116ce597a8287/android/src/main/java/com/espidfprovisioning/EspIdfProvisioningModule.kt#L136).
* then in method `createESPDevice`, if the device exist in the `espDevices` cache, it [returns immediately](https://github.com/orbital-systems/react-native-esp-idf-provisioning/blob/7a08cc20b0dc1e2c6a55ae240fd116ce597a8287/android/src/main/java/com/espidfprovisioning/EspIdfProvisioningModule.kt#L215) without filling the Pop. And the result is that PoP is never used.

I made a patch and it seems to work for my case. Not know if there is any other cases. I don't check the property `android.bluetooth.BluetoothDevice.uuids` because it always null in my case: the bluetooth device is not null by its uuids is null.
[fix_proofOfPossession_is_never_set_patch.txt](https://github.com/orbital-systems/react-native-esp-idf-provisioning/files/13804732/fix_proofOfPossession_is_never_set_patch.txt)

**Comment by fazal26** [comment]
Facing the same issue.

**Comment by mateogianolio** [comment]
Hey! I got the same issue on 0.2.12 when testing yesterday (however my error was `onCharacteristicWrite, status : 133`). But it worked after applying #36. Did you rebuild the app after updating the package? Our device uses proof of possession.

**Comment by fazal26** [comment]
@mateogianolio thanks for reaching out, I've given the app following permissions:
`<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />

    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>

    <uses-permission
        android:name="android.permission.NEARBY_WIFI_DEVICES"
        android:usesPermissionFlags="neverForLocation" />`
        
        Plus I'm using the following configuration prior to device connection:
        `const prefix = 'PROV_';
      const transport = ESPTransport.ble;
      const security = ESPSecurity.secure;`
      
      and while connecting I'm using a simple string as a pop:
      ` device
        .connect('pop123456')`
        
        All the permissions are granted, the device scanning is working, device gets connected but on wifi scan call it fails, I've updated the package to 0.2.13 and still getting this.
        
        any help much appreciated thanks.
![Screenshot 2024-01-25 at 4 05 19 PM](https://github.com/orbital-systems/react-native-esp-idf-provisioning/assets/31815563/f3e02830-11c5-4167-8833-46772962a8b0)

**Comment by fazal26** [comment]
And when I try to provision the device by manually passing ssid and password (bypassing the wifi scan function) i get the same error.

**Comment by x3beche** [comment]
Make sure that you did correct configurations on esp side for security version 1: 
![image](https://github.com/user-attachments/assets/4945b4d1-5ba3-4943-a3e7-5c281ac0c5b2)
