### ISSUE TITLE
Connect method doesn't resolve (BLE)

### ISSUE THREAD

**Issue by mtoninelli** [orbital-systems/react-native-esp-idf-provisioning#56]
Hi Mateo,

I'm so happy to have found this package. It's exactly what I'm looking for. Thanks for sharing it!

I've installed and run succesfully the example. I'm unsing BLE.

The bluetooth scan works fine and it lists the device.

I got stuck on the follow step when I try to connect it (without any security).

This connect method never resolves.
https://github.com/orbital-systems/react-native-esp-idf-provisioning/blob/f8ff66fcfc207d1829f5dcc66c7b5e03e49d5c21/src/index.tsx#L63

Any ideas?

Thank you very much

**Comment by mateogianolio** [comment]
Thank you for your kind words! Are you using iOS or android? Do you have access to logs on the esp device?

**Comment by mateogianolio** [comment]
Does it happen all the time or just after you've already connected once? I've had some issues when connecting to a single device several times (without disconnecting in-between)

**Comment by nat-jones** [comment]
@tygoegmond Did you end up finding a fix/workaround for this?

**Comment by mateogianolio** [comment]
#73 was fixed in 0.4.1 which might — or might not, I'm not familiar with expo — affect expo installations. Also esp-idf-provisioning-ios version in 0.4.0. If possible, please try the latest version.

**Comment by mateogianolio** [comment]
Latest version is compatible with react-native 0.76.2 and new architecture, should hopefully work with expo as well.
