### ISSUE TITLE
Issue with connection to device that causes stacking of further flow(`searchWifiList`, `provision`)

### ISSUE THREAD

**Issue by anzamih** [orbital-systems/react-native-esp-idf-provisioning#60]
Hi guys,
I'm trying to use your library and face with weird bug. 

When I connect my device with `connect` method it connects but then nothing happens (searching for wi-fi list and then  connecting should be then). 

Machine OS - MacOS 14.1.2
Device OS  - Android 14

Here is my piece of code
<img width="697" alt="Screenshot 2024-06-21 at 09 57 46" src="https://github.com/orbital-systems/react-native-esp-idf-provisioning/assets/173201360/d8871dec-5927-4ffc-93ec-0c243a3d02e8">

And logs from terminal. We can see some errors here. They could be the reason of my problem
<img width="1728" alt="Screenshot 2024-06-21 at 09 56 51" src="https://github.com/orbital-systems/react-native-esp-idf-provisioning/assets/173201360/9aa5ea31-16f0-41fa-960a-eade4f368834">
<img width="1728" alt="Screenshot 2024-06-21 at 09 57 13" src="https://github.com/orbital-systems/react-native-esp-idf-provisioning/assets/173201360/c1d67a74-4943-4b04-8cc5-1948e6bd22a0">

UPD:
I found out that here is issue with EspIdfProvisioningPackage 
<img width="1728" alt="Screenshot 2024-06-21 at 13 25 58" src="https://github.com/orbital-systems/react-native-esp-idf-provisioning/assets/173201360/3e721d6b-130d-4339-bf90-b7489d2c3188">

**Comment by mateogianolio** [comment]
In your project I don't see any reference to react-native-esp-idf-provisioning in the list of packages. Have you installed the package correctly?
![Screenshot 2024-09-04 at 09 49 09](https://github.com/user-attachments/assets/ac04284b-2070-4e54-9589-0c7a2a4cb4e6)
