### ISSUE TITLE
Send custom data during provisioning

### ISSUE THREAD

**Issue by grasmash** [orbital-systems/react-native-esp-idf-provisioning#61]
Hello,

I'd like to send additional metadata to the device during provisioning, in addition to the ssid and passphrase. It looks like this is supported in the upstream library: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/provisioning/wifi_provisioning.html#additional-endpoints

How can I do this with this using [react-native-esp-idf-provisioning](https://github.com/orbital-systems/react-native-esp-idf-provisioning)?

**Comment by grasmash** [comment]
Ah. Looks like here https://github.com/orbital-systems/react-native-esp-idf-provisioning/blob/master/example/src/SendDataScreen.tsx it is done with `const espResponse = await props.route.params.device.sendData(path, data);` ?

**Comment by mateogianolio** [comment]
Exactly! Same as #67, it's possible but docs are missing in README. Refer to the example app for now :)
