### ISSUE TITLE
[Error: Request to send data to device failed with error: BLE characteristic does not exist.] on ios

### ISSUE THREAD

**Issue by Akilan-katomaran** [orbital-systems/react-native-esp-idf-provisioning#62]
when trying to send custom data in ios ([Error: Request to send data to device failed with error: BLE characteristic does not exist.]) this error occur , in android works fine

**Comment by grasmash** [comment]
I'm hitting the same thing.

**Comment by mateogianolio** [comment]
You need to set up the custom data endpoint in your ESP device

**Comment by grasmash** [comment]
True.
