### ISSUE TITLE
Custom endPoint

### ISSUE THREAD

**Issue by Mit4el** [orbital-systems/react-native-esp-idf-provisioning#67]
hi, is sending a custom endpoint implemented in your library? couldn't find it in the code, can you specify?

**Comment by mateogianolio** [comment]
Hey, do you mean sending data to custom path? It's not in the readme, but in the example app there is a screen for sending custom data. 

https://github.com/orbital-systems/react-native-esp-idf-provisioning/blob/master/example/src/SendDataScreen.tsx

**Comment by mateogianolio** [comment]
README (or separate API docs) should be added but will create another issue for that. Please refer to the example app for now, which has examples for data transmission.
