### ISSUE TITLE
Blufi

### ISSUE THREAD

**Issue by nat-jones** [orbital-systems/react-native-esp-idf-provisioning#68]
Excited about this project! Does this project work with Blufi Protocol and ESP32 Blufi example app? If so, can we have an example showing the setup.

[esp blufi example app](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/blufi)

**Comment by mateogianolio** [comment]
The Blufi protocol is not supported by this library. This is only for ESP IDF unified provisioning (https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/provisioning/provisioning.html).
